[[plugins]]
package = "netlify-build-plugin-pushover"

  [plugins.inputs]
    successMessage = "deployed the site successfully ğŸ‰" #Optional
    errorMessage = "Latest build failed ğŸ˜±\n\nCheck build's log for more details" #Optional